# Generated by Django 3.2.7 on 2021-10-06 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteProduct', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
