# Generated by Django 3.2.7 on 2021-10-07 05:37

from django.db import migrations, models
import favoriteProduct.validation


class Migration(migrations.Migration):

    dependencies = [
        ('favoriteProduct', '0002_alter_customer_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorite',
            name='product_id',
            field=models.CharField(max_length=200, validators=[favoriteProduct.validation.check_product_existence]),
        ),
    ]
